# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "github-markdown"
gem "github-linguist"
gem "gollum", github: "gollum/gollum", branch: "5.x"
gem "asciidoctor"
gem "wikicloth"
gem "org-ruby"
gem "RedCloth"
gem "gollum-rugged_adapter"
